name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: docker
    container:
      image: golang:1.25-alpine
    steps:
      - name: Install deps
        run: apk add --no-cache git nodejs

      - uses: actions/checkout@v4

      - name: Run tests
        run: go test -mod=vendor -count=1 ./...

  build:
    runs-on: docker
    container:
      image: golang:1.25-alpine
    needs: test
    steps:
      - name: Install deps
        run: apk add --no-cache git nodejs

      - uses: actions/checkout@v4

      - name: Build binary
        run: CGO_ENABLED=0 GOOS=linux go build -mod=vendor -ldflags="-s -w" -o asiakirjat .

      - uses: actions/upload-artifact@v3
        with:
          name: asiakirjat
          path: asiakirjat

  docker:
    runs-on: docker
    container:
      image: gcr.io/kaniko-project/executor:debug
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Configure registry credentials
        run: |
          mkdir -p /kaniko/.docker
          echo "{\"auths\":{\"git.mmo.to\":{\"auth\":\"$(echo -n "${{ secrets.REGISTRY_USER }}:${{ secrets.REGISTRY_TOKEN }}" | base64)\"}}}" > /kaniko/.docker/config.json

      - name: Build and push Docker image
        run: >
          /kaniko/executor
          --context .
          --dockerfile Dockerfile
          --destination git.mmo.to/qwc-open/asiakirjat:latest
          --destination git.mmo.to/qwc-open/asiakirjat:${{ github.sha }}
